
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import User
from User import User

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/frame0")

start = False

current_user = None

def start_session(window):
    global start
    print("se apreto")
    start = True
    window.destroy()

def register_user(entry_1, entry_2):
    global current_user 

    name = entry_1.get()
    description = entry_2.get()
    user = User(name, description)
    print(user.name)
    print(user.description)
    current_user = user

def add_values(values):
    global current_user

    current_user.values = values

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def start_gui():

    window = Tk()

    window.geometry("797x566")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 566,
        width = 797,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        302.7492980957031,
        54.79375076293945,
        977.9853820800781,
        730.0298347473145,
        fill="#FFFFFF",
        outline="")

    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        496.69512939453125,
        87.41666412353516,
        image=image_image_1
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(
        486.0,
        116.0,
        image=image_image_2
    )

    image_image_3 = PhotoImage(
        file=relative_to_assets("image_3.png"))
    image_3 = canvas.create_image(
        456.2298583984375,
        160.20486450195312,
        image=image_image_3
    )

    image_image_4 = PhotoImage(
        file=relative_to_assets("image_4.png"))
    image_4 = canvas.create_image(
        447.2298583984375,
        215.5520782470703,
        image=image_image_4
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        564.8183898925781,
        188.18054962158203,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#DCDCDF",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=412.33679580688477,
        y=171.57638549804688,
        width=304.9631881713867,
        height=31.208328247070312
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        564.8183898925781,
        243.5277557373047,
        image=entry_image_2
    )
    entry_2 = Entry(
        bd=0,
        bg="#DDDCDF",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=412.33679580688477,
        y=226.923583984375,
        width=304.9631881713867,
        height=31.208343505859375
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: register_user(entry_1, entry_2),
        relief="flat"
    )
    button_1.place(
        x=404.0,
        y=318.79998779296875,
        width=320.0,
        height=44.27777099609375
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: start_session(window),
        relief="flat"
    )
    button_2.place(
        x=404.0,
        y=409.0,
        width=320.4951171875,
        height=44.293731689453125
    )

    image_image_5 = PhotoImage(
        file=relative_to_assets("image_5.png"))
    image_5 = canvas.create_image(
        189.51597118377686,
        260.7374954223633,
        image=image_image_5
    )
    window.resizable(False, False)
    window.mainloop()
